### ISSUE TITLE
您好，运行test报错了

### ISSUE THREAD

**Issue by zhengshengjie666** [bobaoapae/wpp-api-ws#6]
12月 13, 2021 12:28:02 下午 br.com.zapia.wpp.api.ws.WhatsAppClient onMessage
严重: OnMessage
java.lang.IllegalStateException: Invalid message received
	at br.com.zapia.wpp.api.ws.NoiseHandler.decodeFrame(NoiseHandler.java:118)
	at br.com.zapia.wpp.api.ws.WhatsAppClient.onMessage(WhatsAppClient.java:1573)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
	at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:936)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:889)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.base/java.lang.Thread.run(Thread.java:833)

12月 13, 2021 12:28:02 下午 br.com.zapia.wpp.api.ws.WhatsAppClient onClose
严重: Ws Disconnected with code: {1006} and reason: {}. fromRemote: {true}

**Comment by bobaoapae** [comment]
Hello, MD Version is not working for now, just initial implementation
